### ISSUE TITLE
Upgrade to CDH 6.3.x

### ISSUE THREAD

**Issue by mfirry** [hbase-rdd/hbase-rdd#38]
It should be pretty simple. Basically upgrading (check [CDH 6.3.4 Packaging](https://docs.cloudera.com/documentation/enterprise/6/release-notes/topics/rg_cdh_63_packaging.html#cdh_630_packaging))

- `hbaseVersion`: current `2.1.0-cdh6.2.0` => should be set to `2.1.0-cdh6.3.4`
- `hadoopVersion`: current `3.0.0-cdh6.2.0` => should be ste to `3.0.0-cdh6.3.4`
- `sparkVersion`: current `2.4.3` => I think it's safe to use the latest `2.4` published for Scala 2.11 and 2.12 (it should be `2.4.7`)

**Comment by mfirry** [comment]
Maybe we can ask somebody from Cloudera if versions are correct. Maybe @patrickangeles or @busbey (Sorry to bother guys).

**Comment by busbey** [comment]
FYI I no longer work for cloudera.

I would recommend using the [maven coordinates docs for C6.3.4](https://docs.cloudera.com/documentation/enterprise/6/release-notes/topics/rg_cdh_63_maven_artifacts.html#cdh_634_maven_artifacts) to get this info.  The ones you have listed for Hadoop and HBase are correct. If you're trying to use the Spark packaging that comes with C6 then your version number is incorrect. Additionally, I think C6's spark is only packaged for scala 2.11.

that said, why use this project rather than the hbase-spark integration that comes in C6? it already has a bunch of RDD support (and then some)

**Comment by mfirry** [comment]
Thanks for the heads-up! We've been developing and using this internally and are quite happy (we found this to be better for our purpose ~ and we're mainly using it with Scala). Not sure the status of the thing you mention. Care to share a link?

Also, if you do know, does Cloudera CDP work any differently? We're also investigating moving to it at some point.

Thanks anyways!

**Comment by busbey** [comment]
> Not sure the status of the thing you mention. Care to share a link?

Sure, the feature has been under development in the hbase community for quite some time but only started making releases in 2020:

* http://hbase.apache.org/book.html#spark
* https://github.com/apache/hbase-connectors/tree/master/spark

In CDH it's been a supported shipped feature since ~CDH5.7 I think?

> Also, if you do know, does Cloudera CDP work any differently? We're also investigating moving to it at some point.

There's a [Cloudera community write up "HBase-Spark in CDP"](https://community.cloudera.com/t5/Community-Articles/HBase-Spark-in-CDP/ta-p/294868) that does a good overview of the version of this feature Cloudera has shipped across CDH, HDP, and CDP versions. The focus there is on scala. If [pyspark comes up there's a recent blog post series that has a good intro to the integration](https://blog.cloudera.com/building-a-machine-learning-application-with-cloudera-data-science-workbench-and-operational-database-part-1-the-set-up-basics/).

**Comment by mfirry** [comment]
> The focus there is on scala
Our focus as well!

Thank you so much!

**Comment by mfirry** [comment]
> https://github.com/apache/hbase-connectors/tree/master/spark

Yeah, I knew this bit.

> The focus there is on scala

Our focus as well!

Thank you so much!
